import AIUsageLog from "../models/AIUsageLog.js";

// @desc    AI demo endpoint (proxy)
// @route   POST /api/ai/demo
// @access  Public (with rate limiting)
export const aiDemo = async (req, res, next) => {
  try {
    const { type, prompt } = req.body;

    // Validate inputs
    if (!type || !prompt) {
      return res.status(400).json({
        success: false,
        message: "Please provide type and prompt",
      });
    }

    if (!["text", "image"].includes(type)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid type. Must be "text" or "image"',
      });
    }

    // Get IP address
    const ip =
      req.headers["x-forwarded-for"] || req.connection.remoteAddress || "";

    let result = "";

    // NOTE: This is a demo implementation
    // In production, you would call the actual OpenAI API or other AI service
    // For now, we'll return mock responses

    if (type === "text") {
      // Mock text generation
      result = `This is a demo AI response for: "${prompt}". 
      
      In a production environment, this would be generated by an AI model like GPT-3.5 or GPT-4. 
      
      To implement this feature, you would:
      1. Install the OpenAI SDK (npm install openai)
      2. Add your OpenAI API key to .env
      3. Call the OpenAI API with your prompt
      4. Return the AI-generated response
      
      For now, this is a placeholder response to demonstrate the feature.`;
    } else if (type === "image") {
      // Mock image prompt description
      result = `Image description for: "${prompt}"
      
      This would normally generate an actual image using DALL-E or Stable Diffusion.
      
      Image concept: A highly detailed, photorealistic rendering based on your prompt.
      Style: ${
        prompt.includes("futuristic")
          ? "Cyberpunk, neon-lit"
          : "Modern, vibrant"
      }
      Composition: Dynamic perspective with emphasis on visual impact.
      
      To implement real image generation:
      - Use OpenAI's DALL-E API
      - Or use Stable Diffusion API
      - Store generated images in cloud storage (AWS S3, Cloudinary, etc.)
      - Return the image URL to the frontend`;
    }

    // Log the usage
    await AIUsageLog.create({
      type,
      prompt,
      result,
      ip,
      tokens: Math.floor(prompt.length / 4), // Rough estimate
      success: true,
    });

    res.status(200).json({
      success: true,
      result,
      demo: true, // Indicates this is a demo response
    });

    /* 
    // PRODUCTION CODE (uncomment and configure):
    
    import OpenAI from 'openai';
    
    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
    
    if (type === 'text') {
      const completion = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages: [{ role: 'user', content: prompt }],
        max_tokens: 150,
      });
      
      result = completion.choices[0].message.content;
    } else if (type === 'image') {
      const image = await openai.images.generate({
        model: 'dall-e-3',
        prompt: prompt,
        n: 1,
        size: '1024x1024',
      });
      
      result = image.data[0].url;
    }
    */
  } catch (error) {
    // Log failed attempt
    try {
      await AIUsageLog.create({
        type: req.body.type,
        prompt: req.body.prompt,
        result: error.message,
        ip:
          req.headers["x-forwarded-for"] || req.connection.remoteAddress || "",
        success: false,
      });
    } catch (logError) {
      console.error("Failed to log AI error:", logError);
    }

    next(error);
  }
};

// @desc    Get AI usage statistics
// @route   GET /api/admin/ai/stats
// @access  Private (Admin)
export const getAIStats = async (req, res, next) => {
  try {
    const totalRequests = await AIUsageLog.countDocuments();
    const successfulRequests = await AIUsageLog.countDocuments({
      success: true,
    });
    const textRequests = await AIUsageLog.countDocuments({ type: "text" });
    const imageRequests = await AIUsageLog.countDocuments({ type: "image" });

    const recentLogs = await AIUsageLog.find()
      .sort({ createdAt: -1 })
      .limit(10)
      .select("type prompt createdAt success");

    res.status(200).json({
      success: true,
      stats: {
        totalRequests,
        successfulRequests,
        failedRequests: totalRequests - successfulRequests,
        textRequests,
        imageRequests,
      },
      recentLogs,
    });
  } catch (error) {
    next(error);
  }
};

export default { aiDemo, getAIStats };
