import Project from "../models/Project.js";

// @desc    Create a new project
// @route   POST /api/projects
// @access  Private (Admin only)
export const createProject = async (req, res, next) => {
  try {
    const {
      title,
      description,
      category,
      imageUrl,
      technologies,
      features,
      liveUrl,
      githubUrl,
      featured,
      order,
    } = req.body;

    // Validate required fields
    if (!title || !description) {
      return res.status(400).json({
        success: false,
        message: "Please provide title and description",
      });
    }

    // Create project (slug will be auto-generated by pre-save hook)
    const project = await Project.create({
      title,
      description,
      category,
      imageUrl,
      technologies: technologies || [],
      features: features || [],
      liveUrl,
      githubUrl,
      featured: featured || false,
      order: order || 0,
    });

    res.status(201).json({
      success: true,
      data: project,
    });
  } catch (error) {
    // Handle duplicate slug error
    if (error.code === 11000) {
      return res.status(400).json({
        success: false,
        message: "A project with similar title already exists",
      });
    }
    next(error);
  }
};

// @desc    Get all projects
// @route   GET /api/projects
// @access  Public
export const getProjects = async (req, res, next) => {
  try {
    // Optional query parameters for filtering
    const { featured, category } = req.query;

    let query = {};

    if (featured !== undefined) {
      query.featured = featured === "true";
    }

    if (category) {
      query.category = category;
    }

    const projects = await Project.find(query).sort({
      featured: -1,
      order: 1,
      createdAt: -1,
    });

    res.status(200).json({
      success: true,
      count: projects.length,
      data: projects,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single project by slug or ID
// @route   GET /api/projects/:identifier
// @access  Public
export const getProject = async (req, res, next) => {
  try {
    const { identifier } = req.params;

    // Try to find by slug first, then by ID
    let project = await Project.findOne({ slug: identifier });

    if (!project) {
      // If not found by slug, try by ID
      project = await Project.findById(identifier);
    }

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    res.status(200).json({
      success: true,
      data: project,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update project
// @route   PUT /api/projects/:id
// @access  Private (Admin only)
export const updateProject = async (req, res, next) => {
  try {
    const {
      title,
      description,
      category,
      imageUrl,
      technologies,
      features,
      liveUrl,
      githubUrl,
      featured,
      order,
    } = req.body;

    let project = await Project.findById(req.params.id);

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    // Update fields (slug will be auto-generated if title changes)
    project = await Project.findByIdAndUpdate(
      req.params.id,
      {
        title,
        description,
        category,
        imageUrl,
        technologies,
        features,
        liveUrl,
        githubUrl,
        featured,
        order,
      },
      {
        new: true,
        runValidators: true,
      }
    );

    res.status(200).json({
      success: true,
      data: project,
    });
  } catch (error) {
    // Handle duplicate slug error
    if (error.code === 11000) {
      return res.status(400).json({
        success: false,
        message: "A project with similar title already exists",
      });
    }
    next(error);
  }
};

// @desc    Delete project
// @route   DELETE /api/projects/:id
// @access  Private (Admin only)
export const deleteProject = async (req, res, next) => {
  try {
    const project = await Project.findById(req.params.id);

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    await project.deleteOne();

    res.status(200).json({
      success: true,
      data: {},
      message: "Project deleted successfully",
    });
  } catch (error) {
    next(error);
  }
};

export default {
  createProject,
  getProjects,
  getProject,
  updateProject,
  deleteProject,
};
